name: deploy on prodd
on:
  pull_request:
    branches:
    - master
    types:
    - synchronize
jobs:
  prod:
    name: deploy on stage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: deploy master
      run: cat README.md

